# Generated by Django 4.0.5 on 2022-06-29 01:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0004_contato_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='descricao',
            new_name='descrição',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='mostrar',
        ),
        migrations.AddField(
            model_name='contato',
            name='data_criação',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
