var = int(input('Digite um número: '))

print('O número digitado foi: {}, segue abaixo sua tabuada.'.format(var))
print('{} x 1 = {}'.format(var, var*1))
print('{} x 2 = {}'.format(var, var*2))
print('{} x 3 = {}'.format(var, var*3))
print('{} x 4 = {}'.format(var, var*4))
print('{} x 5 = {}'.format(var, var*5))
print('{} x 6 = {}'.format(var, var*6))
print('{} x 7 = {}'.format(var, var*7))
print('{} x 8 = {}'.format(var, var*8))
print('{} x 9 = {}'.format(var, var*9))
print('{} x 10 = {}'.format(var, var*10))