# Generated by Django 4.0.6 on 2022-07-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='qtd_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade Total'),
            preserve_default=False,
        ),
    ]
