# Generated by Django 4.0.6 on 2022-07-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Confirme seu E-Mail'),
        ),
    ]
