nome = str(input('Digite seu nome: ')).strip()
print('Analisando seu nome...')
print('Seu nome em maiúsculas é {}'.format(nome.upper()))
print('Seu nome me minúsculas é {}' .format(nome.lower()))
print('Seu nome tem ao todo tem {} letras' .format(len(nome)-nome.count(' ')))
print('Seus primeiro nome tem {} letras' .format(nome.find(' ')))
